application: the-tangibles
version: 1
runtime: python
api_version: 1

handlers:

- url: /room.*
  script: apprtc.py
  secure: always
  
- url: /workspace.*
  script: apprtc.py
  secure: always

- url: /.*
  script: apprtc.py
  secure: always
  
inbound_services:
- channel_presence
