application: the-tangibles
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: webapp2
  version: 2.5.1

handlers:
- url: /room.*
  script: tangibles.py
  secure: always
  
- url: /workspace.*
  script: tangibles.py
  secure: always
  
- url: /lobby.*
  script: tangibles.py
  secure: always

- url: /.*
  script: tangibles.py
  secure: always
  
inbound_services:
- channel_presence
